eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostName: localhost
management:
  endpoints:
    web:
     exposure:
        include: health
spring:
  datasource:
    username: root
    password: pganesh
    url: jdbc:mysql://localhost:3306/newRestApi
    driverClassName: com.mysql.cj.jdbc.Driver
  boot:
    admin:
      client:
        url : http://localhost:1111/
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

springdoc:
  swagger-ui:
    path: swagger-ui.html
